#!/bin/sh
do_wivi_config () {
	
		echo "Booting using default WiVi-AP config"
		[ -f /rom/wivi.tgz ] && {
			echo "--WiVi config restore--"
			cd /
			cp /rom/wivi.tgz /tmp
			tar xzf /tmp/wivi.tgz
			rm -f /tmp/wivi.tgz
			touch /wiviboot
			sync
		}
		
	
}
do_wivi_config

